version: "3.8"
services: 
  nest_service:
    container_name: nest_service
    build: .
    ports:
      - 3000:3000
    networks:
      - private_network
    environment:
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_CACHED_ALIVE=300
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    networks:
      - private_network
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis_server:redis:6379
    ports:
    - "8081:8081"
    networks:
      - private_network
networks:
    private_network:
      name: private_network